/**
 * US-005  Generate a 6-character invite code to share with my child
 * US-006  Enter an invite code to join my parent's family
 * US-007  See all my children with their gem balances
 */
import { test, expect } from '@playwright/test';
import {
  TEST_PASSWORD, signUp, gotoWelcome, restoreSession, clickTab, assertOnParentDashboard,
  signUpChildForTest, SUPABASE_WAIT,
} from './helpers';

// Spec-specific emails — avoids collision with other spec files sharing the same TS
const STS = Date.now();
const SPEC_PARENT_EMAIL = `test.parent.02.${STS}@kidreward-test.com`;
const SPEC_CHILD_EMAIL  = `test.child.02.${STS}@kidreward-test.com`;
const SPEC_PARENT_NAME  = `TestParent02_${STS}`;
const SPEC_CHILD_NAME   = `TestChild02_${STS}`;

// Shared state across tests in this file
let parentState: any;
let childState: any;
let inviteCode = '';

test.beforeAll(async ({ browser }) => {
  test.setTimeout(120_000);
  const p = await browser.newPage();
  await signUp(p, 'Parent', SPEC_PARENT_NAME, SPEC_PARENT_EMAIL);
  parentState = await p.context().storageState();
  await p.close();

  childState = await signUpChildForTest(browser, SPEC_CHILD_NAME, SPEC_CHILD_EMAIL);
});

test.describe('Family Pairing', () => {

  test('US-005 | Parent can generate a 6-character invite code (email required)', async ({ page }) => {
    await restoreSession(page, parentState, '/dashboard');
    await assertOnParentDashboard(page);

    // Navigate to My Kids → Invite
    await clickTab(page, 'My Kids');
    await page.getByText('Send Invite →', { exact: true }).first().dispatchEvent('click');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    // Email is required for child invites — fill it before creating
    const emailInput = page.getByTestId('child-email-input');
    if (await emailInput.isVisible({ timeout: 3000 }).catch(() => false)) {
      await emailInput.fill(SPEC_CHILD_EMAIL);
    }

    // Create invite code
    const createBtn = page.getByTestId('create-invite-btn');
    if (await createBtn.isVisible({ timeout: 3000 }).catch(() => false)) {
      await createBtn.dispatchEvent('click');
      await page.waitForLoadState('networkidle');
      await page.waitForTimeout(2000);
    }

    // Invite code displayed as large isolated text — exactly 6 uppercase chars/digits
    const codeElement = page.getByText(/^[A-Z0-9]{6}$/);
    await expect(codeElement.first()).toBeVisible({ timeout: 10_000 });

    inviteCode = (await codeElement.first().textContent())?.trim() ?? '';
    expect(inviteCode).toHaveLength(6);
    console.log(`Generated invite code: ${inviteCode}`);
  });

  test('Parent invite shows child email on existing invite card', async ({ page }) => {
    test.skip(!inviteCode, 'Skipped — invite not yet generated');

    await restoreSession(page, parentState, '/dashboard');
    await assertOnParentDashboard(page);

    await clickTab(page, 'My Kids');
    // Use either button label (no-kids state: "Send Invite →", with-kids: "+ Invite")
    const sendBtn = page.getByText('Send Invite →', { exact: true });
    const addBtn  = page.getByText('+ Invite', { exact: true });
    if (await sendBtn.isVisible({ timeout: 3000 }).catch(() => false)) {
      await sendBtn.first().dispatchEvent('click');
    } else {
      await addBtn.first().dispatchEvent('click');
    }
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    // The invite card shows the email in the "LOCKED TO EMAIL" badge
    await expect(page.getByText(SPEC_CHILD_EMAIL, { exact: false })).toBeVisible({ timeout: 10_000 });
  });

  test('US-006 | Child can join family using invite code', async ({ page }) => {
    test.skip(!inviteCode, 'Skipped — invite code not generated by previous test');

    // Restore child session (child is authenticated but not yet in a family)
    await restoreSession(page, childState, '/');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    // Should be on join screen (app redirects child with no family here)
    await expect(
      page.getByText('Join Your Family!').or(page.getByPlaceholder('ABC123')).first()
    ).toBeVisible({ timeout: 15_000 });

    // Enter invite code — wait for React re-render (6/6 hint) confirms button is enabled
    const input = page.getByPlaceholder('ABC123');
    await input.fill(inviteCode);
    await expect(page.getByText('6/6 characters')).toBeVisible({ timeout: 10_000 });
    // dispatchEvent bypasses CSS pointer-events without needing the full PressResponder chain
    await page.getByText("Let's Go!").first().dispatchEvent('click');
    // Wait for the async join() to complete (Supabase insert + refreshFamily)
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(3000);

    // After joining, navigate to home — gives the navigation time to complete
    await page.goto('/');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(2000);

    // Should now see child dashboard with missions
    await expect(
      page.getByText('Active Missions').or(page.getByText('No missions yet')).first()
    ).toBeVisible({ timeout: 15_000 });
  });

  test('US-007 | Parent sees child in My Kids list with gem balance', async ({ page }) => {
    test.skip(!inviteCode, 'Skipped — pairing not completed');

    await restoreSession(page, parentState, '/dashboard');
    await assertOnParentDashboard(page);

    await clickTab(page, 'My Kids');
    await page.waitForLoadState('networkidle');

    await expect(page.getByText(SPEC_CHILD_NAME, { exact: false }).first()).toBeVisible({ timeout: 10_000 });
    await expect(page.getByText('💎 Balance').or(page.getByText('0')).first()).toBeVisible();
  });

  test('Parent invite: create button disabled until child email is entered', async ({ page }) => {
    // Navigate directly to the invite screen (avoids unstable tab-click navigation)
    await restoreSession(page, parentState, '/children/invite');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    // If an existing invite is shown, skip (button not visible)
    const emailInputVisible = await page.getByTestId('child-email-input').isVisible({ timeout: 3000 }).catch(() => false);
    if (!emailInputVisible) { return; }

    // With empty email, create button has aria-disabled=true (React Native Web uses aria-disabled, not HTML disabled)
    const btn = page.getByTestId('create-invite-btn');
    await expect(btn).toHaveAttribute('aria-disabled', 'true', { timeout: 5_000 });

    // After filling email, button becomes interactive (aria-disabled=false or attribute removed)
    await page.getByTestId('child-email-input').fill('child@example.com');
    await page.waitForTimeout(300);
    const ariaDisabled = await btn.getAttribute('aria-disabled');
    expect(ariaDisabled === null || ariaDisabled === 'false').toBeTruthy();
  });

  test('Invalid invite code shows error', async ({ page }) => {
    // Test via the signup-child flow (no child session needed — avoids slow REST signup)
    await gotoWelcome(page);
    await page.getByText('Join with invite code', { exact: false }).click();
    await page.waitForLoadState('networkidle');

    await page.getByTestId('invite-code-input').fill('XXXXXX');
    page.once('dialog', async d => d.accept());
    await page.getByTestId('validate-code-btn').click();
    await page.waitForTimeout(5000);

    // Should still be on step 1 (invalid code — not advanced to account creation step)
    await expect(page.getByTestId('invite-code-input')).toBeVisible({ timeout: 10_000 });
  });

});
