/**
 * US-005  Generate a 6-character invite code to share with my child
 * US-006  Enter an invite code to join my parent's family
 * US-007  See all my children with their gem balances
 */
import { test, expect } from '@playwright/test';
import {
  TS, parentEmail, childEmail, TEST_PASSWORD, PARENT_NAME, CHILD_NAME,
  signUp, login, signOut, assertOnParentDashboard,
} from './helpers';

// Shared state across tests in this file
let inviteCode = '';

test.describe('Family Pairing', () => {

  test('US-005 | Parent can generate a 6-character invite code', async ({ page }) => {
    await signUp(page, 'Parent', PARENT_NAME, parentEmail());
    await assertOnParentDashboard(page);

    // Navigate to Invite screen
    await page.getByText('My Kids').click();
    await page.getByText('Invite').click();
    await page.waitForLoadState('networkidle');

    // Create invite code
    const createBtn = page.getByText('Create Invite Code');
    if (await createBtn.isVisible()) {
      await createBtn.click();
      await page.waitForLoadState('networkidle');
    }

    // Invite code should be visible — 6 uppercase alphanumeric characters
    const codeElement = page.locator('text=/[A-Z0-9]{6}/');
    await expect(codeElement.first()).toBeVisible({ timeout: 10_000 });

    // Grab the code for use in next test
    const codeText = await codeElement.first().textContent();
    inviteCode = codeText?.match(/[A-Z0-9]{6}/)?.[0] ?? '';
    expect(inviteCode).toHaveLength(6);
    console.log(`Generated invite code: ${inviteCode}`);
  });

  test('US-006 | Child can join family using invite code', async ({ page }) => {
    test.skip(!inviteCode, 'Skipped — invite code not generated by previous test');

    await signUp(page, 'Child', CHILD_NAME, childEmail());
    // Should be on join screen
    await expect(page.getByText('Join Your Family')).toBeVisible({ timeout: 10_000 });

    // Enter invite code
    const input = page.getByPlaceholder('ABC123');
    await input.fill(inviteCode);
    await page.getByText("Let's Go!").click();
    await page.waitForLoadState('networkidle');

    // Should now see child dashboard with missions
    await expect(
      page.getByText('Active Missions').or(page.getByText('No missions yet'))
    ).toBeVisible({ timeout: 15_000 });
  });

  test('US-007 | Parent sees child in My Kids list with gem balance', async ({ page }) => {
    test.skip(!inviteCode, 'Skipped — pairing not completed');

    await login(page, parentEmail());
    await assertOnParentDashboard(page);

    // Go to My Kids
    await page.getByText('My Kids').click();
    await page.waitForLoadState('networkidle');

    // Child should appear
    await expect(page.getByText(CHILD_NAME, { exact: false })).toBeVisible({ timeout: 10_000 });

    // Gem balance (starts at 0) should be visible
    await expect(page.getByText('💎 Balance').or(page.getByText('0'))).toBeVisible();
  });

  test('Invalid invite code shows error', async ({ page }) => {
    const email = `invalid.test.${Date.now()}@kidreward-test.com`;
    await signUp(page, 'Child', `InvalidTest${Date.now()}`, email);

    await expect(page.getByText('Join Your Family')).toBeVisible({ timeout: 10_000 });

    await page.getByPlaceholder('ABC123').fill('XXXXXX');
    await page.getByText("Let's Go!").click();

    await expect(
      page.getByText('invalid').or(page.getByText('expired')).or(page.getByText('not found'))
    ).toBeVisible({ timeout: 10_000 });
  });

});
