/**
 * US-005  Generate a 6-character invite code to share with my child
 * US-006  Enter an invite code to join my parent's family
 * US-007  See all my children with their gem balances
 */
import { test, expect } from '@playwright/test';
import {
  TEST_PASSWORD, signUp, gotoWelcome, restoreSession, clickTab, assertOnParentDashboard,
  signUpChildForTest, SUPABASE_WAIT, SUPABASE_URL, SUPABASE_ANON_KEY,
} from './helpers';

// Spec-specific emails — avoids collision with other spec files sharing the same TS
const STS = Date.now();
const SPEC_PARENT_EMAIL = `test.parent.02.${STS}@kidreward-test.com`;
const SPEC_CHILD_EMAIL  = `test.child.02.${STS}@kidreward-test.com`;
const SPEC_PARENT_NAME  = `TestParent02_${STS}`;
const SPEC_CHILD_NAME   = `TestChild02_${STS}`;

// Shared state across tests in this file
let parentState: any;
let childState: any;
let inviteCode = '';

test.beforeAll(async ({ browser }) => {
  test.setTimeout(120_000);
  const p = await browser.newPage();
  await signUp(p, 'Parent', SPEC_PARENT_NAME, SPEC_PARENT_EMAIL);
  parentState = await p.context().storageState();
  await p.close();

  childState = await signUpChildForTest(browser, SPEC_CHILD_NAME, SPEC_CHILD_EMAIL);
});

test.describe('Family Pairing', () => {

  test('US-005 | Parent can generate a 6-character invite code (email required)', async ({ page }) => {
    await restoreSession(page, parentState, '/dashboard');
    await assertOnParentDashboard(page);

    // Navigate to My Kids → Invite
    await clickTab(page, 'My Kids');
    await page.getByText('Send Invite →', { exact: true }).first().dispatchEvent('click');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    // Open the "Invite a Child" form
    const addBtn = page.getByTestId('add-child-invite-btn');
    if (await addBtn.isVisible({ timeout: 3000 }).catch(() => false)) {
      await addBtn.click();
      await page.waitForTimeout(500);
    }

    // Fill email and create
    const emailInput = page.getByTestId('child-email-input');
    if (await emailInput.isVisible({ timeout: 3000 }).catch(() => false)) {
      await emailInput.fill(SPEC_CHILD_EMAIL);
    }

    const createBtn = page.getByTestId('create-invite-btn');
    if (await createBtn.isVisible({ timeout: 3000 }).catch(() => false)) {
      await createBtn.dispatchEvent('click');
      await page.waitForLoadState('networkidle');
      await page.waitForTimeout(2000);
    }

    // Invite code displayed as large isolated text — exactly 6 uppercase chars/digits
    const codeElement = page.getByText(/^[A-Z0-9]{6}$/);
    await expect(codeElement.first()).toBeVisible({ timeout: 10_000 });

    inviteCode = (await codeElement.first().textContent())?.trim() ?? '';
    expect(inviteCode).toHaveLength(6);
    console.log(`Generated invite code: ${inviteCode}`);
  });

  test('Parent invite shows child email on existing invite card', async ({ page }) => {
    test.skip(!inviteCode, 'Skipped — invite not yet generated');

    await restoreSession(page, parentState, '/children/invite');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    // The invite card shows the email in the "LOCKED TO EMAIL" badge
    await expect(page.getByText(SPEC_CHILD_EMAIL, { exact: false })).toBeVisible({ timeout: 10_000 });
  });

  test('US-006 | Child can join family using invite code', async ({ page }) => {
    test.skip(!inviteCode, 'Skipped — invite code not generated by previous test');

    // Restore child session (child is authenticated but not yet in a family)
    await restoreSession(page, childState, '/');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    // Should be on join screen (app redirects child with no family here)
    await expect(
      page.getByText('Join Your Family!').or(page.getByPlaceholder('ABC123')).first()
    ).toBeVisible({ timeout: 15_000 });

    // Enter invite code — wait for React re-render (6/6 hint) confirms button is enabled
    const input = page.getByPlaceholder('ABC123');
    await input.fill(inviteCode);
    await expect(page.getByText('6/6 characters')).toBeVisible({ timeout: 10_000 });
    await page.getByText("Let's Go!").first().dispatchEvent('click');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(3000);

    // After joining, navigate to home
    await page.goto('/');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(2000);

    await expect(
      page.getByText('Active Missions').or(page.getByText('No missions yet')).first()
    ).toBeVisible({ timeout: 15_000 });
  });

  test('US-007 | Parent sees child in My Kids list with gem balance', async ({ page }) => {
    test.skip(!inviteCode, 'Skipped — pairing not completed');

    await restoreSession(page, parentState, '/dashboard');
    await assertOnParentDashboard(page);

    await clickTab(page, 'My Kids');
    await page.waitForLoadState('networkidle');

    await expect(page.getByText(SPEC_CHILD_NAME, { exact: false }).first()).toBeVisible({ timeout: 10_000 });
    await expect(page.getByText('💎 Balance').or(page.getByText('0')).first()).toBeVisible();
  });

  test('Parent invite: create button disabled until child email is entered', async ({ page }) => {
    await restoreSession(page, parentState, '/children/invite');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    // Open the invite form
    const addBtn = page.getByTestId('add-child-invite-btn');
    await expect(addBtn).toBeVisible({ timeout: 5_000 });
    await addBtn.click();
    await page.waitForTimeout(300);

    // With empty email, create button has aria-disabled=true
    const btn = page.getByTestId('create-invite-btn');
    await expect(btn).toHaveAttribute('aria-disabled', 'true', { timeout: 5_000 });

    // After filling email, button becomes interactive
    await page.getByTestId('child-email-input').fill('child@example.com');
    await page.waitForTimeout(300);
    const ariaDisabled = await btn.getAttribute('aria-disabled');
    expect(ariaDisabled === null || ariaDisabled === 'false').toBeTruthy();
  });

  test('Multiple parallel invites — two child invites visible simultaneously', async ({ page }) => {
    test.setTimeout(60_000);
    const ts = Date.now();

    await restoreSession(page, parentState, '/children/invite');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    const email1 = `multi1.${ts}@kidreward-test.com`;
    const email2 = `multi2.${ts}@kidreward-test.com`;

    // Create first invite
    await page.getByTestId('add-child-invite-btn').click();
    await page.getByTestId('child-email-input').fill(email1);
    await page.getByTestId('create-invite-btn').dispatchEvent('click');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(2000);

    // Create second invite
    await page.getByTestId('add-child-invite-btn').click();
    await page.getByTestId('child-email-input').fill(email2);
    await page.getByTestId('create-invite-btn').dispatchEvent('click');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(2000);

    // Both emails should be visible
    await expect(page.getByText(email1, { exact: false })).toBeVisible({ timeout: 10_000 });
    await expect(page.getByText(email2, { exact: false })).toBeVisible({ timeout: 10_000 });
  });

  test('Cancel invite — invite card disappears from list', async ({ page }) => {
    test.setTimeout(60_000);
    const ts = Date.now();
    const email = `cancel.${ts}@kidreward-test.com`;

    await restoreSession(page, parentState, '/children/invite');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    // Create an invite to cancel
    await page.getByTestId('add-child-invite-btn').click();
    await page.getByTestId('child-email-input').fill(email);
    await page.getByTestId('create-invite-btn').dispatchEvent('click');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(2000);

    // Find and note the code shown
    await expect(page.getByText(email, { exact: false })).toBeVisible({ timeout: 10_000 });

    // Click the cancel button (✕) — new invites are prepended, so the one
    // we just created is the first card in the list, not the last.
    const cancelBtns = page.locator('[data-testid^="cancel-btn-"]');
    await cancelBtns.first().click();
    await page.waitForTimeout(500);

    // Confirm the alert
    page.once('dialog', async d => d.accept());
    // React Native Alert on web — look for "Cancel invite" button
    const confirmBtn = page.getByText('Cancel invite', { exact: true });
    if (await confirmBtn.isVisible({ timeout: 2000 }).catch(() => false)) {
      await confirmBtn.click();
    }
    await page.waitForTimeout(1000);

    // Email should be gone from list
    await expect(page.getByText(email, { exact: false })).not.toBeVisible({ timeout: 5_000 });
  });

  test('Resend invite — new code replaces old code', async ({ page }) => {
    test.setTimeout(60_000);
    const ts = Date.now();
    const email = `resend.${ts}@kidreward-test.com`;

    await restoreSession(page, parentState, '/children/invite');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1000);

    // Create an invite
    await page.getByTestId('add-child-invite-btn').click();
    await page.getByTestId('child-email-input').fill(email);
    await page.getByTestId('create-invite-btn').dispatchEvent('click');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(2000);

    await expect(page.getByText(email, { exact: false })).toBeVisible({ timeout: 10_000 });

    // Note the original code
    const codeEl = page.getByText(/^[A-Z0-9]{6}$/).first();
    const originalCode = (await codeEl.textContent())?.trim() ?? '';
    expect(originalCode).toHaveLength(6);

    // Click Resend — new invites are prepended, so the one we just created
    // is the first card in the list, not the last.
    const resendBtns = page.locator('[data-testid^="resend-btn-"]');
    await resendBtns.first().click();
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(2500);

    // A new code should be visible — different from original
    const newCodeEl = page.getByText(/^[A-Z0-9]{6}$/).first();
    await expect(newCodeEl).toBeVisible({ timeout: 10_000 });
    const newCode = (await newCodeEl.textContent())?.trim() ?? '';
    expect(newCode).toHaveLength(6);
    expect(newCode).not.toBe(originalCode);

    // Email still associated with new invite
    await expect(page.getByText(email, { exact: false })).toBeVisible({ timeout: 5_000 });
  });

  test('Regression: email-less invite (pre-migration) shows creation form not stale card', async ({ page }) => {
    test.setTimeout(120_000);
    const ts = Date.now();
    const pEmail = `regression.noemail.${ts}@kidreward-test.com`;

    // Create a fresh parent
    const p = await page.context().browser()!.newPage();
    await signUp(p, 'Parent', `RegParent${ts}`, pEmail);
    const pAuth = await p.context().storageState();
    await p.close();

    // Extract JWT + family_id
    const jwt = pAuth.origins?.flatMap((o: any) => o.localStorage ?? [])
      .map((i: any) => { try { const d = JSON.parse(i.value); return d?.access_token; } catch { return null; } })
      .find(Boolean);
    const userId = pAuth.origins?.flatMap((o: any) => o.localStorage ?? [])
      .map((i: any) => { try { const d = JSON.parse(i.value); return d?.user?.id; } catch { return null; } })
      .find(Boolean);
    const famResp = await fetch(`${SUPABASE_URL}/rest/v1/families?parent_id=eq.${userId}&select=id`,
      { headers: { apikey: SUPABASE_ANON_KEY, Authorization: `Bearer ${jwt}` } });
    const [{ id: familyId }] = await famResp.json();

    // Insert an invite WITHOUT email (simulates pre-migration data)
    const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
    let code = ''; for (let i = 0; i < 6; i++) code += chars[Math.floor(Math.random() * chars.length)];
    await fetch(`${SUPABASE_URL}/rest/v1/invites`, {
      method: 'POST',
      headers: { apikey: SUPABASE_ANON_KEY, Authorization: `Bearer ${jwt}`, 'Content-Type': 'application/json', Prefer: 'return=minimal' },
      body: JSON.stringify({ family_id: familyId, code, invite_type: 'child', created_by: userId, expires_at: new Date(Date.now() + 7 * 86400000).toISOString() }),
    });

    // Open invite screen — must see the add button (not a stale email-less card)
    await restoreSession(page, pAuth);
    await page.goto('/children/invite');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(1500);

    // "Invite a Child" button visible (empty-state UI shown, not stale card)
    await expect(page.getByTestId('add-child-invite-btn')).toBeVisible({ timeout: 10_000 });
    // The old email-less invite code must NOT be shown
    await expect(page.getByText(code)).not.toBeVisible({ timeout: 3_000 });
  });

  test('Invalid invite code shows error', async ({ page }) => {
    await gotoWelcome(page);
    await page.getByText('Join with invite code', { exact: false }).click();
    await page.waitForLoadState('networkidle');

    await page.getByTestId('invite-code-input').fill('XXXXXX');
    page.once('dialog', async d => d.accept());
    await page.getByTestId('validate-code-btn').click();
    await page.waitForTimeout(5000);

    // Should still be on step 1 (invalid code — not advanced to account creation step)
    await expect(page.getByTestId('invite-code-input')).toBeVisible({ timeout: 10_000 });
  });

});
